# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem "rake"

gem "rabbit-slide-oss-gate-introduction-japanese"           # OSSGateの紹介
gem "rabbit-slide-oss-gate-workshop-tutorial-preparation"   # 準備
gem "rabbit-slide-oss-gate-workshop-tutorial-overview"      # OSS開発手順
gem "rabbit-slide-oss-gate-workshop-tutorial-feedback"      # フィードバック
gem "rabbit-slide-oss-gate-workshop-tutorial-conclusion"    # まとめ
